language: node_js
node_js:
- '0.10'

install:
  - "npm install"
  - "gem install compass"
  - "bower install"

script:
  - "grunt build"

deploy:
  provider: divshot
  environment:
    master: development
  api_key:
    secure: H/AiT/iDX8BEmxpNR0h37Wkad7KQkf0eezFarwkdgBCnKORcUR2fyd6PrX4bP4DdVkKqm941VyZ2qyKVd73MYxwpdaUf0ZzLR+3O9tIdm9yxyeeHZEWiOpZrgEH4cu+ebnW2/6+gulUUQkn743+cqIuKnqcGAYTLXBfj9EsPxJY=
  skip_cleanup: true